/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarRoomRouteImport } from './routes/war-room'
import { Route as VentureIntelRouteImport } from './routes/venture-intel'
import { Route as TimelapseRouteImport } from './routes/timelapse'
import { Route as IndexRouteImport } from './routes/index'

const WarRoomRoute = WarRoomRouteImport.update({
  id: '/war-room',
  path: '/war-room',
  getParentRoute: () => rootRouteImport,
} as any)
const VentureIntelRoute = VentureIntelRouteImport.update({
  id: '/venture-intel',
  path: '/venture-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelapseRoute = TimelapseRouteImport.update({
  id: '/timelapse',
  path: '/timelapse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/timelapse': typeof TimelapseRoute
  '/venture-intel': typeof VentureIntelRoute
  '/war-room': typeof WarRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/timelapse': typeof TimelapseRoute
  '/venture-intel': typeof VentureIntelRoute
  '/war-room': typeof WarRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/timelapse': typeof TimelapseRoute
  '/venture-intel': typeof VentureIntelRoute
  '/war-room': typeof WarRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/timelapse' | '/venture-intel' | '/war-room'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/timelapse' | '/venture-intel' | '/war-room'
  id: '__root__' | '/' | '/timelapse' | '/venture-intel' | '/war-room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimelapseRoute: typeof TimelapseRoute
  VentureIntelRoute: typeof VentureIntelRoute
  WarRoomRoute: typeof WarRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/war-room': {
      id: '/war-room'
      path: '/war-room'
      fullPath: '/war-room'
      preLoaderRoute: typeof WarRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venture-intel': {
      id: '/venture-intel'
      path: '/venture-intel'
      fullPath: '/venture-intel'
      preLoaderRoute: typeof VentureIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timelapse': {
      id: '/timelapse'
      path: '/timelapse'
      fullPath: '/timelapse'
      preLoaderRoute: typeof TimelapseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimelapseRoute: TimelapseRoute,
  VentureIntelRoute: VentureIntelRoute,
  WarRoomRoute: WarRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
